site_name: "Guia de Desenvolvimento - Cognitivo.ai"
site_description: "Documento criado para guiar o Desenvolvimento de projetos, especialmente na etapa de programaÃ§Ã£o, na Cognitivo.ai"
site_author: "Cognitivo.ai"
copyright: "Â© 2025 Cognitivo.ai. All rights reserved."
theme:
  name: "material"
  logo: "image/logo_cog.png"
  palette:
    primary: "white"
  favicon: "image/icon.png"

  features:
    - navigation.tabs

  locale: pt_BR

nav:
  - Home: "index.md"
  - Geral:
    - Vamos ao CÃ³digo ğŸ‘¨ğŸ¼â€ğŸ’»: "global/code.md"
    - O git ğŸŒ³: "global/git.md"
    - DocumentaÃ§Ãµes ğŸ“: "global/documentation.md"
    - RepositÃ³rios ğŸ“‚: "global/repositories.md"

  - Data Science:
    - Start: "data_science/start.md"

  - Engenharia de Dados:
    - Start: "data_eng/start.md"

  - Analytics:
    - Start: "analytics/start.md"

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  footer: "Â© 2025 Cognitivo.ai. All rights reserved."
